FROM ubuntu:24.04
LABEL maintainer="wekan"
LABEL org.opencontainers.image.ref.name="ubuntu"
LABEL org.opencontainers.image.version="24.04"
LABEL org.opencontainers.image.source="https://github.com/wekan/wekan"

ARG DEBIAN_FRONTEND=noninteractive

ENV BUILD_DEPS="apt-utils gnupg gosu wget bzip2 g++ curl libarchive-tools build-essential git ca-certificates python3 unzip"

ENV \
    DEBUG=false \
    NODE_VERSION=v14.21.4 \
    NPM_VERSION=6.14.17 \
    ARCHITECTURE=linux-x64 \
    WITH_API=true \
    WRITABLE_PATH=/data \
    S3=""

RUN <<EOR
set -o xtrace

useradd --user-group --system --home-dir /home/wekan wekan
apt-get update --assume-yes
apt-get install --assume-yes --no-install-recommends ${BUILD_DEPS}

cd /tmp
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/node-v14.21.4-linux-x64.tar.gz"
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/SHASUMS256.txt"
grep "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt" | shasum -a 256 -c -
tar xzf "node-v14.21.4-linux-x64.tar.gz" -C /usr/local --strip-components=1 --no-same-owner
rm "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt"
ln -s "/usr/local/bin/node" "/usr/local/bin/nodejs"
npm install -g npm@6.14.17 --production

mkdir /data
chown wekan --recursive /data
EOR

COPY .build/bundle /build

RUN <<EOR
set -o xtrace
cd /build/programs/server
chmod u+w *.json
npm install --production
npm install fibers --save-dev
cd /build/programs/server/npm/node_modules/meteor/accounts-password
npm remove bcrypt
npm install bcrypt --production

apt-get remove --purge --assume-yes ${BUILD_DEPS}
apt-get autoremove --assume-yes
apt-get clean --assume-yes
rm -Rf /tmp/*
rm -Rf /var/lib/apt/lists/*
rm -Rf /var/cache/apt
rm -Rf /var/lib/apt/lists
EOR

USER wekan

ENV PORT=8080
EXPOSE $PORT

WORKDIR /home/wekan/app
CMD ["bash", "-c", "ulimit -s 65500; exec node /build/main.js"]
