FROM ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND=noninteractive

ENV BUILD_DEPS="apt-utils gnupg gosu wget bzip2 g++ curl libarchive-tools build-essential git ca-certificates python3 p7zip-full zip unzip unp"
ENV PATH="/home/wekan/.meteor:/home/wekan/.npm-global/bin:/usr/local/bin:${PATH}"

RUN <<EOR
set -eux
apt-get update --assume-yes
apt-get install --assume-yes --no-install-recommends ${BUILD_DEPS}
useradd --user-group --system --create-home --home-dir /home/wekan wekan
mkdir -p /home/wekan/.npm-global
chown --recursive wekan:wekan /home/wekan

cd /tmp
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/node-v14.21.4-linux-x64.tar.gz"
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/SHASUMS256.txt"
grep "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt" | sha256sum -c -
tar xzf "node-v14.21.4-linux-x64.tar.gz" -C /usr/local --strip-components=1 --no-same-owner
rm "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt"
ln -s "/usr/local/bin/node" "/usr/local/bin/nodejs"

npm install -g npm@6.14.17 --production
gosu wekan npm config set prefix /home/wekan/.npm-global
gosu wekan npm install -g @mapbox/node-pre-gyp node-gyp meteor@2.14 --unsafe-perm
node --version
npm --version
gosu wekan meteor --version
EOR

WORKDIR /home/wekan/app
COPY --chown=wekan:wekan . .

RUN <<EOR
set -eux
rm -rf .git
rm -rf .build/bundle node_modules .meteor/local .build
gosu wekan meteor npm install --production
gosu wekan meteor build .build --directory --platforms=web.browser
find .build -maxdepth 3 -type f -name main.js -print
test -f .build/bundle/main.js
rm -rf .build/bundle/programs/web.browser.legacy

cd .build/bundle/programs/server
rm -rf node_modules
chmod u+w *.json
gosu wekan meteor npm install --production
gosu wekan npm install fibers --save-dev
if [ -d npm/node_modules/meteor/accounts-password ]; then
  cd npm/node_modules/meteor/accounts-password
  gosu wekan meteor npm remove bcrypt
  gosu wekan meteor npm install bcrypt --production
fi

cd /home/wekan/app/.build/bundle
find . -type d -name '*-garbage*' -prune -exec rm -rf {} +
find . -name '*phantom*' -exec rm -rf {} +
find . -name '.*.swp' -exec rm -f {} +
find . -name '*.swp' -exec rm -f {} +
EOR

FROM ubuntu:24.04
LABEL maintainer="wekan"
LABEL org.opencontainers.image.ref.name="ubuntu"
LABEL org.opencontainers.image.version="24.04"
LABEL org.opencontainers.image.source="https://github.com/wekan/wekan"

ARG DEBIAN_FRONTEND=noninteractive

ENV RUNTIME_DEPS="ca-certificates wget"
ENV \
  DEBUG=false \
  NODE_VERSION=v14.21.4 \
  NPM_VERSION=6.14.17 \
  ARCHITECTURE=linux-x64 \
  WITH_API=true \
  WRITABLE_PATH=/data \
  S3=""

RUN <<EOR
set -eux
useradd --user-group --system --home-dir /home/wekan wekan
apt-get update --assume-yes
apt-get install --assume-yes --no-install-recommends ${RUNTIME_DEPS}

cd /tmp
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/node-v14.21.4-linux-x64.tar.gz"
wget "https://github.com/wekan/node-v14-esm/releases/download/v14.21.4/SHASUMS256.txt"
grep "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt" | sha256sum -c -
tar xzf "node-v14.21.4-linux-x64.tar.gz" -C /usr/local --strip-components=1 --no-same-owner
rm "node-v14.21.4-linux-x64.tar.gz" "SHASUMS256.txt"
ln -s "/usr/local/bin/node" "/usr/local/bin/nodejs"
npm install -g npm@6.14.17 --production

mkdir /data
chown wekan --recursive /data

apt-get remove --purge --assume-yes ${RUNTIME_DEPS}
apt-get autoremove --assume-yes
apt-get clean --assume-yes
rm -Rf /tmp/*
rm -Rf /var/lib/apt/lists/*
rm -Rf /var/cache/apt
rm -Rf /var/lib/apt/lists
EOR

COPY --from=builder /home/wekan/app/.build/bundle /build

USER wekan

ENV PORT=8080
EXPOSE $PORT

WORKDIR /home/wekan/app
CMD ["bash", "-c", "ulimit -s 65500; exec node /build/main.js"]
